setting up runner docker

diff --git a/runner/Dockerfile b/runner/Dockerfile
--- a/runner/Dockerfile
+++ b/runner/Dockerfile
@@ -1,26 +1,30 @@
-# Kaggle docker container config
-FROM gcr.io/kaggle-images/python:v10
+FROM ubuntu:18.04
 
-# RUN apt-get install -y --no-install-recommends gnupg2 curl ca-certificates apt-transport-https
+# Basic prereqs
+RUN apt update
 RUN apt-get update
-RUN apt-get install zip -y
-RUN apt-get install vim -y
-# set up basic .vimrc file
-RUN echo -e ":syntax on\n:set expandtab\n:set number" > ~/.vimrc
+RUN apt-get install -y openjdk-8-jdk
+RUN apt-get install -y wget
+RUN apt-get install -y gnupg
+RUN apt-get install -y zip
+RUN apt-get install -y vim
 
-# RUN pip uninstall -y tensorflow
-# Downgrade tensorflow to avoid core dump in Ubuntu VM
-# Distributor ID: Ubuntu
-# Description: Ubuntu 16.04.4 LTS
-# Release: 16.04
-# Codename: xenial
-# root@daa5dbbc0f6b:/# python3 -c 'import tensorflow'
-# 2018-05-04 18:09:06.153333: F tensorflow/core/platform/cpu_feature_guard.cc:36] The TensorFlow library was compiled to use AVX2 instructions, but these aren't available on your machine.
-# Aborted (core dumped)
-# Known issue: https://github.com/tensorflow/tensorflow/issues/17411
-# RUN pip install tensorflow==1.15
+# install/setup python
+RUN apt-get install -y python3.7
+RUN apt-get install -y python3-pip
+RUN apt-get install 2to3
+RUN ln -s $(which python3.7) /usr/bin/python
+RUN ln -s $(which python3.7) /usr/bin/python3 --force
+RUN ln -s $(which pip3) /usr/bin/pip
+RUN pip install -U pip
+RUN apt-get install -y git
 
-# Python analysis tools
+# packages needed for kaggle scripts
+ADD requirements.txt requirements.txt
+# add true as xargs may result in 123 exit code
+RUN (cat requirements.txt | grep -v "#" | xargs -I {} pip install {}) || true
+
+# PL analysis tools
 RUN git clone https://github.com/josepablocam/python-pl
 RUN pip install -e python-pl
 
@@ -29,14 +33,11 @@ ADD transfer.zip transfer.zip
 RUN unzip transfer.zip -d transfer
 RUN pip install -e transfer
 
-# # install ipython to succesfully run
-# RUN pip install ipython
-#
-# # copy in data and source for script to execute
-# # top-level directory with [projectx/[scripts, input]]
-# ADD program_data/ program_data/
-#
-# # copy in the driver
-# ADD run_pipeline.py run_pipeline.py
-#
-# ENTRYPOINT ["python", "run_pipeline.py"]
+# copy in data and source for script to execute
+# top-level directory with [projectx/[scripts, input]]
+ADD program_data/ program_data/
+
+# copy in the driver
+ADD run_pipeline.py run_pipeline.py
+
+ENTRYPOINT ["python", "run_pipeline.py"]
